# DA algorithm many to one
## author : kei ikegami

In [1]:
;cat ikegamida_mm.jl

function ikegamida_mm(prop_prefs::Matrix{Int}, resp_prefs::Matrix{Int}, caps::Vector{Int})
    
    # set up
    prop_num, resp_num = size(prop_prefs)[2], size(resp_prefs)[2]
    match_or_unmatch = Array(Bool, prop_num)
    for i in 1:prop_num
        match_or_unmatch[i] = true
    end
    prop_matched, resp_matched = ones(Int64, prop_num) + resp_num, ones(Int64, sum(caps)) + prop_num
    
    prop_rank = Array(Int64, (resp_num + 1, prop_num))
    resp_rank = Array(Int64, (prop_num + 1, resp_num))
    
    sorting = Array(Int64, (resp_num + 1, 2))
    sorting[:, 1] = collect(1:(resp_num + 1))
    for i in 1:prop_num
        sorting[:, 2] = prop_prefs[:, i]
        prop_rank[:,i] = sortrows(sorting, by = x->(x[2]))[:,1]
        sorting = sortrows(sorting, by = x->(x[1]))
    end
    
    sorting2 = Array(Int64, (prop_num + 1, 2))
    sorting2[:, 1] = collect(1:(prop_num + 1))
    for i in 1:resp_num
        sorting2[:, 2] = resp_prefs[:, i]
        resp_rank[:,i] = sortrows(sorting2, by

### example

In [2]:
include("ikegamida_mm.jl");

In [3]:
s_prefs = [3, 1, 5, 4, 0, 2,
                   1, 3, 4, 2, 5, 0,
                   4, 5, 3, 1, 2, 0,
                   3, 4, 1, 5, 0, 2,
                   1, 4, 2, 0, 3, 5,
                   4, 3, 2, 1, 5, 0,
                   2, 5, 1, 3, 0, 4,
                   1, 3, 2, 5, 4, 0,
                   4, 1, 5, 0, 2, 3,
                   3, 1, 5, 2, 4, 0,
                   5, 4, 1, 3, 2, 0]
        s_prefs = reshape(s_prefs, 6, 11)


6x11 Array{Int64,2}:
 3  1  4  3  1  4  2  1  4  3  5
 1  3  5  4  4  3  5  3  1  1  4
 5  4  3  1  2  2  1  2  5  5  1
 4  2  1  5  0  1  3  5  0  2  3
 0  5  2  0  3  5  0  4  2  4  2
 2  0  0  2  5  0  4  0  3  0  0

In [4]:
c_prefs = [3, 7, 9, 11, 5, 4, 10, 8, 6, 1,
                   2, 0, 5, 7, 10, 6, 8, 2, 3, 11,
                   0, 1, 4, 9, 11, 6, 8, 3, 2, 4,
                   7, 1, 10, 0, 5, 9, 10, 1, 2, 11,
                   4, 9, 5, 3, 6, 8, 0, 7, 2, 4,
                   10, 7, 6, 1, 8, 3, 11, 9, 0, 5]
        c_prefs = reshape(c_prefs, 12, 5)

12x5 Array{Int64,2}:
  3   5  11  10   2
  7   7   6   1   4
  9  10   8   2  10
 11   6   3  11   7
  5   8   2   4   6
  4   2   4   9   1
 10   3   7   5   8
  8  11   1   3   3
  6   0  10   6  11
  1   1   0   8   9
  2   4   5   0   0
  0   9   9   7   5

In [5]:
caps = [4, 1, 3, 2, 1]

5-element Array{Int64,1}:
 4
 1
 3
 2
 1

In [6]:
ikegamida_mm(s_prefs, c_prefs, caps)

([3,1,4,3,1,3,2,1,4,1,5],[5,10,8,2,7,6,4,1,9,3,11],[1,5,6,9,11,12])

### test failed ?

In [7]:
include("test_deferred_acceptance.jl");

ikegamida_mm: many-to-one: Test Failed
  Expression: c_matched_computed == c_matched_expected
   Evaluated: [5,10,8,2,7,6,4,1,9,3,11] == [2,5,8,10,7,1,4,6,3,9,11]
 in record at /Users/susu/.julia/v0.4/BaseTestNext/src/BaseTestNext.jl:320
 in do_test at /Users/susu/.julia/v0.4/BaseTestNext/src/BaseTestNext.jl:192
 [inlined code] from /Users/susu/DA_Julia/test_deferred_acceptance.jl:115
 in anonymous at no file:0
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_string at loading.jl:282
 in execute_request_0x535c5df2 at /Users/susu/.julia/v0.4/IJulia/src/execute_request.jl:183
 in eventloop at /Users/susu/.julia/v0.4/IJulia/src/IJulia.jl:143
 in anonymous at task.jl:447
Test Summary:                           | Pass  Fail  Total
Testing ikegamida_mm.jl                 |    9     1     10
  ikegamida_mm: one-to-one              |    4    

LoadError: LoadError: LoadError: Some tests did not pass: 9 passed, 1 failed, 0 errored.
while loading /Users/susu/DA_Julia/test_deferred_acceptance.jl, in expression starting on line 17
while loading In[7], in expression starting on line 1

テストに通らないのは合格者の並び方が違うから？

池上のコードでは大学側にとって好ましい順に並べているが、テスト結果ではそうではない？

実際受け入れている番号は、テストと池上のコードで一致している。