# DA algorithm many to one
## author : kei ikegami

[code](https://github.com/keiikegami/DA_Julia/blob/master/ikegamida_mm.jl)

### example

In [1]:
include("ikegamida_mm.jl");

In [2]:
s_prefs = [3, 1, 5, 4, 0, 2,
                   1, 3, 4, 2, 5, 0,
                   4, 5, 3, 1, 2, 0,
                   3, 4, 1, 5, 0, 2,
                   1, 4, 2, 0, 3, 5,
                   4, 3, 2, 1, 5, 0,
                   2, 5, 1, 3, 0, 4,
                   1, 3, 2, 5, 4, 0,
                   4, 1, 5, 0, 2, 3,
                   3, 1, 5, 2, 4, 0,
                   5, 4, 1, 3, 2, 0]
        s_prefs = reshape(s_prefs, 6, 11)


6x11 Array{Int64,2}:
 3  1  4  3  1  4  2  1  4  3  5
 1  3  5  4  4  3  5  3  1  1  4
 5  4  3  1  2  2  1  2  5  5  1
 4  2  1  5  0  1  3  5  0  2  3
 0  5  2  0  3  5  0  4  2  4  2
 2  0  0  2  5  0  4  0  3  0  0

In [3]:
c_prefs = [3, 7, 9, 11, 5, 4, 10, 8, 6, 1,
                   2, 0, 5, 7, 10, 6, 8, 2, 3, 11,
                   0, 1, 4, 9, 11, 6, 8, 3, 2, 4,
                   7, 1, 10, 0, 5, 9, 10, 1, 2, 11,
                   4, 9, 5, 3, 6, 8, 0, 7, 2, 4,
                   10, 7, 6, 1, 8, 3, 11, 9, 0, 5]
        c_prefs = reshape(c_prefs, 12, 5)

12x5 Array{Int64,2}:
  3   5  11  10   2
  7   7   6   1   4
  9  10   8   2  10
 11   6   3  11   7
  5   8   2   4   6
  4   2   4   9   1
 10   3   7   5   8
  8  11   1   3   3
  6   0  10   6  11
  1   1   0   8   9
  2   4   5   0   0
  0   9   9   7   5

In [4]:
caps = [4, 1, 3, 2, 1]

5-element Array{Int64,1}:
 4
 1
 3
 2
 1

In [5]:
ikegamida_mm(s_prefs, c_prefs, caps)

([3,1,4,3,1,3,2,1,4,1,5],[5,10,8,2,7,6,4,1,9,3,11],[1,5,6,9,11,12])

In [6]:
include("test_deferred_acceptance.jl");

Test Summary:           | Pass  Total
Testing ikegamida_mm.jl |   10     10
