## Ikegami

In [6]:
using DefferedAcceptance

In [2]:
m_prefs = [[3], [3, 2, 1], [1, 3, 2], [3, 1]]
f_prefs = [[2, 3], [2, 3, 4, 1], [4, 1, 2]]

3-element Array{Array{Int64,1},1}:
 [2,3]    
 [2,3,4,1]
 [4,1,2]  

In [ ]:
a = DefferedAcceptance.ikegami

In [3]:
DefferedAcceptance.ikegami(m_prefs, f_prefs)

([0,2,1,3],[3,2,4])

test

In [1]:
Pkg.test("DefferedAcceptance")

INFO: Testing DefferedAcceptance


one-to-one: Vector of Vectors: Error During Test
  Got an exception of type BoundsError outside of a @test
  BoundsError: attempt to access 0-element Array{Int64,1} at index [1]
   in setindex!(::Array{Int64,1}, ::Int64, ::Int64) at ./array.jl:415
   in setindex!(::Array{Int64,1}, ::Int64, ::Int64) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
   in ikegami(::Array{Array{Int64,1},1}, ::Array{Array{Int64,1},1}) at /Users/susu/.julia/v0.5/DefferedAcceptance/src/DefferedAcceptance.jl:13
   in macro expansion; at /Users/susu/.julia/v0.5/DefferedAcceptance/test/runtests.jl:109 [inlined]
   in macro expansion; at ./test.jl:672 [inlined]
   in macro expansion; at /Users/susu/.julia/v0.5/DefferedAcceptance/test/runtests.jl:98 [inlined]
   in macro expansion; at ./test.jl:672 [inlined]
   in anonymous at ./<missing>:?
   in include_from_node1(::String) at ./loading.jl:488
   in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/l

ERROR: LoadError: Some tests did not pass: 2 passed, 0 failed, 1 errored, 0 broken.
 in finish(::Base.Test.DefaultTestSet) at ./test.jl:495
 in macro expansion; at ./test.jl:679 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/susu/.julia/v0.5/DefferedAcceptance/test/runtests.jl, in expression starting on line 12
=========================[ ERROR: DefferedAcceptance ]==========================

failed process: Process(`/Applications/Julia-0.5.app/Contents/Resources/julia/bin/julia -Ccore2 -J/Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color

LoadError: DefferedAcceptance had test errors

test2

In [14]:
m, n = 5, 4
m_prefs = [[1, 2, 3, 4], [4, 2, 3, 1],[4, 3, 1, 2],[1, 4, 3, 2],[1, 2, 4]]
f_prefs = [[2, 3, 1, 4, 5],[3, 1, 2, 4, 5],[5, 4, 1, 2, 3],[1, 4, 5, 2, 3]]

4-element Array{Array{Int64,1},1}:
 [2,3,1,4,5]
 [3,1,2,4,5]
 [5,4,1,2,3]
 [1,4,5,2,3]

In [10]:
DefferedAcceptance.ikegami(m_prefs, f_prefs)

([1,2,3,4,0],[1,2,3,4])

In [15]:
DefferedAcceptance.ikegami(f_prefs, m_prefs)

([2,3,4,1],[4,1,2,3,0])

test3

In [25]:
m_prefs = [[1, 2, 3, 4],[2, 1, 4, 3],[3, 4, 1, 2],[4, 3, 2, 1]]
f_prefs = [[4, 3, 2, 1],[3, 4, 1, 2],[2, 1, 4, 3],[1, 2, 3, 4]]

4-element Array{Array{Int64,1},1}:
 [4,3,2,1]
 [3,4,1,2]
 [2,1,4,3]
 [1,2,3,4]

In [12]:
DefferedAcceptance.ikegami(m_prefs, f_prefs)

([1,2,3,4],[1,2,3,4])

In [20]:
# test通らない？
DefferedAcceptance.ikegami(f_prefs, m_prefs)

LoadError: BoundsError: attempt to access 0-element Array{Int64,1} at index [1]

In [18]:
m = length(m_prefs)
n = length(f_prefs)

m_prefs_2d = Matrix{Int64}(n+1, m)
f_prefs_2d = Matrix{Int64}(m+1, n)

for (t,i) in enumerate(m_prefs)
    if length(i) != n
        new_element = Array(Int, n+1-length(i))
        new_element[1] = 0
        new_element[2:end] = [j for j in range(1,n) if !(j in i)]
        m_prefs[t] = append!(i, new_element)
    else
        m_prefs[t] = push!(i, 0)
    end
    m_prefs_2d[:, t] = m_prefs[t]
end

for (t,i) in enumerate(f_prefs)
    if length(i) != m
        new_element = Array(Int, m+1-length(i))
        new_element[1] = 0
        new_element[2:end] = [j for j in range(1,m) if !(j in i)]
        f_prefs[t] = append!(i, new_element)
    else
        f_prefs[t] = push!(i, 0)
    end
    f_prefs_2d[:, t] = f_prefs[t]
end

In [23]:
# これは通る
ikegamida(f_prefs_2d, m_prefs_2d)

([4,3,2,1],[4,3,2,1])

In [26]:
ikegami(f_prefs, m_prefs)

([4,3,2,1],[4,3,2,1])

In [24]:
function ikegami(a::Vector{Vector{Int}}, b::Vector{Vector{Int}})
    m = length(a)
    n = length(b)

    a_2d = Matrix{Int64}(n+1, m)
    b_2d = Matrix{Int64}(m+1, n)

    for (t,i) in enumerate(a)
        if length(i) != n
            new_element = Array(Int, n+1-length(i))
            new_element[1] = 0
            new_element[2:end] = [j for j in range(1,n) if !(j in i)]
            a[t] = append!(i, new_element)
        else
            a[t] = push!(i, 0)
        end
        a_2d[:, t] = a[t]
    end

    for (t,i) in enumerate(b)
        if length(i) != m
            new_element = Array(Int, m+1-length(i))
            new_element[1] = 0
            new_element[2:end] = [j for j in range(1,m) if !(j in i)]
            b[t] = append!(i, new_element)
        else
            b[t] = push!(i, 0)
        end
        b_2d[:, t] = b[t]
    end

    return ikegamida(a_2d, b_2d)
end


function ikegamida(m_prefs, f_prefs)

    m_num, f_num = size(m_prefs)[2], size(f_prefs)[2]
    m_pool, f_pool = collect(1:m_num), collect(1:f_num)
    match_or_unmatch = Array(Bool, m_num)
    for i in 1:m_num
        match_or_unmatch[i] = true
    end
    m_matched, f_matched = ones(Int64, m_num) + f_num, ones(Int64, f_num) + m_num

    m_rank = Array(Int64, (f_num + 1, m_num))
    f_rank = Array(Int64, (m_num + 1, f_num))

    sorting = Array(Int64, (f_num + 1, 2))
    sorting[:, 1] = collect(1:(f_num + 1))

    for i in 1:m_num
        sorting[:, 2] = m_prefs[:, i]
        m_rank[:,i] = sortrows(sorting, by = x->(x[2]))[:,1]
        sorting = sortrows(sorting, by = x->(x[1]))
    end


    sorting2 = Array(Int64, (m_num + 1, 2))
    sorting2[:, 1] = collect(1:(m_num + 1))

    for i in 1:f_num
        sorting2[:, 2] = f_prefs[:, i]
        f_rank[:,i] = sortrows(sorting2, by = x->(x[2]))[:,1]
        sorting2 = sortrows(sorting2, by = x->(x[1]))
    end

    while sum(match_or_unmatch) > 0
        for i in 1:m_num
            if match_or_unmatch[i] == true

                for j in m_prefs[:, i]

                    if j == 0
                        m_matched[i] = 0
                        match_or_unmatch[i] = false
                        break

                    else
                        no_marriage = f_rank[1, j]

                        if f_rank[i+1, j] < no_marriage

                            if f_matched[j] == m_num + 1
                                f_matched[j] = i
                                m_matched[i] = j
                                match_or_unmatch[i] = false
                                break

                            else

                                if f_rank[f_matched[j]+1, j] > f_rank[i+1, j]
                                    match_or_unmatch[f_matched[j]] = true
                                    f_matched[j] = i
                                    m_matched[i] = j
                                    match_or_unmatch[i] = false
                                    break
                                end
                            end
                        end
                    end
                end
            end
        end
    end

    for (i,t) in enumerate(f_matched)
        if t == m_num + 1
            f_matched[i] = 0
        end
    end

     for (i,t) in enumerate(m_matched)
        if t == f_num + 1
            m_matched[i] = 0
        end
    end

    return m_matched, f_matched
end


ikegamida (generic function with 1 method)