# Rees - Jones (2017) American Economic Review
## Mistaken Play in the Deferred Acceptance Algorithm: Implications for Positive Assortative Matching

DAは選好順序が真の能力なり性質なりをすべて反映していれば、strategy-proof、すなわちマッチングに参加するプレイヤーは自身の選好を偽らずにそのまま報告することが弱支配戦略となることを保証するアルゴリズムである。

しかし、現実のマッチング問題にDAを用いると、必ずしもすべてのプレイヤーが真の選好順序を報告するわけではないことが多数の事例において報告されている。

例えば、学校と生徒のマッチングを考える。

この時学校側が生徒に対して持つ選好順序はなんらかの統一テストなどの結果であることが予想できる。しかし、一回きりの統一テストの結果が生徒の真の能力を完全に反映させるわけではないことは容易に想像できる。体調不良や問題への適性などにより真の能力順序とはいくらか異なる順序をテストの結果として得られていると想定するのがむしろ自然なことである。

本論文はこのような状況下で、生徒側が真の選好順序を報告しないことにより、「より良い学校がより良い生徒とマッチするべき（PAM）」という観点で見たときに社会厚生が改善する可能性のあることを指摘している。

具体的には、能力値の低い学生群が自身の選好を偽って報告した場合に、全員が真の選好順序を報告する倍位よりも社会厚生が高くなることをシミュレーションで示している。以下では論文中で行われたシミュレーションを、シミュレーション回数を少なくして再現する。

## 具体的な設定

10校の学校に対して100人の生徒を10人ずつマッチさせることを考える。

それぞれの真のクオリティは、

$i = 1 \dots 10$として、学校$i$のクオリティが$q_i　= \frac{11 - i}{10}$で、$j = 1 \dots 100$として、生徒$j$のクオリティが$q_j = \frac{101 - j}{100}$

である。

### 学校
学校側が生徒に対して受け取るシグナルは上の真のクオリティを用いて、$s_j= q_j + \epsilon$であるとする。ただし、$\epsilon$は標準正規分布からのランダムサンプルとする。

学校はこのシグナルにしたがって生徒に対する選好順序を構成し、デザイナーに報告する。

### 生徒
生徒側の選好順序におけるmisrepresentationは以下のようにモデル化する。

misrepresentationする生徒の割合を$\left\{0,0.1, 0.2, 0.3, 0.4, 0.5 \right\}$の6パターン用意する。

misrepresentationするかどうかが生徒の性質と送還するかどうかについて、
- 上位の生徒が選好の構成に失敗する
- 下位の生徒が選好の構成に失敗する
- 生徒はランダムに選好の構成に失敗する
の3パターンを用意する。

ここで、「ある生徒がmisrepresentationを起こす」とは、当該生徒の選好がランダムに順序交換させられることを指す。

### シミュレーション
生徒側の選好構成の失敗の仕方により、18通りのシミュレーションを行う。

それぞれの場合において1000回ランダムに選好を真のものからずらしてDAによるマッチングを行う。

それぞれの場合に対して、各学校がマッチした生徒のクオリティの平均値をプロットすることで、misrepresentationがPAMに対してどのような結果をもたらすのかを考察する。

In [46]:
num_stu = 100
num_sch = 10

# caps
cap = 10
caps = round.(Int64, ones(num_sch)*cap)

# school preferences
srand(123)
pre_sch = ones(num_stu, 2)
pre_sch[:, 1] = collect(range(1,num_stu))
pre_sch[:, 2] = collect(1/num_stu:1/num_stu:1) + randn(num_stu)
pre_sch = sortrows(pre_sch, by=x->x[2], rev = true)
school_prefs = [round.(Int64, Array(pre_sch[:, 1])) for i in range(1, num_sch)]

# student preferences


10-element Array{Array{Int64,1},1}:
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]
 [70, 77, 34, 97, 91, 30, 82, 78, 85, 80  …  12, 13, 21, 50, 96, 37, 27, 74, 28, 49]

In [47]:
caps

10-element Array{Int64,1}:
 10
 10
 10
 10
 10
 10
 10
 10
 10
 10

In [20]:
collect(range(1,num_stu))

100-element Array{Int64,1}:
   1
   2
   3
   4
   5
   6
   7
   8
   9
  10
  11
  12
  13
   ⋮
  89
  90
  91
  92
  93
  94
  95
  96
  97
  98
  99
 100